/**
 * Shared helpers for organization and journey scopes. Keeps descriptor
 * extraction in one place so reception (which feeds the classifier) and
 * future consumers (rail, composer, map teaser) can't drift apart.
 *
 * Symmetric with server/personas.ts — the same shape of helper for a
 * different memory axis.
 */

import type { Organization } from "./db/organizations.js";
import type { Journey } from "./db/journeys.js";

export interface ScopeDescriptorOptions {
  /** Append "…" when the value is truncated. */
  ellipsis?: boolean;
  /** Max length in characters before truncation. Default 140. */
  maxLength?: number;
}

/**
 * Extract a short descriptor from an organization or journey scope.
 * Prefers `summary` (generated by the lite model pipeline — Phase 4);
 * falls back to a compact version of briefing + situation while the
 * summary pipeline is not yet live.
 *
 * Returns null only when both summary and the two briefing/situation
 * fields are empty — an unconfigured scope has nothing to route on.
 */
export function extractScopeDescriptor(
  scope: Organization | Journey,
  opts: ScopeDescriptorOptions = {},
): string | null {
  const max = opts.maxLength ?? 140;

  if (scope.summary) {
    const trimmed = scope.summary.trim();
    if (trimmed) return truncate(trimmed, max, opts.ellipsis);
  }

  const joined = [scope.briefing, scope.situation]
    .map((s) => s.trim())
    .filter(Boolean)
    .join(" · ");

  if (!joined) return null;
  const firstLine = joined.split("\n").find((l) => l.trim() && !l.startsWith("#"));
  const base = firstLine ? firstLine.trim() : joined;
  return truncate(base, max, opts.ellipsis);
}

function truncate(text: string, max: number, ellipsis?: boolean): string {
  if (text.length <= max) return text;
  return ellipsis ? text.slice(0, max) + "…" : text.slice(0, max);
}
